### ISSUE TITLE
Error: Version 3.8.7 with arch x64 not found

### ISSUE THREAD

**Issue by rafaelvp-db** [rafaelvp-db/jupyter-to-databricks#2]
Getting this error:

```
Error: Version 3.8.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

While using the following YAML:

```yaml
name: Convert Jupyter to Databricks notebook

on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Convert Jupyter Notebooks to Databricks Notebooks
      uses: rafaelvp-db/jupyter-to-databricks@v1.0
      with:
        inputPath: jupyter
        outputPath: converted
```
